---
title: "Writing Functions"
author: 'Zachary Katz (UNI: zak2132)'
date: "11/4/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(rvest)
library(p8105.datasets)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

## Z scores

```{r}
x_vec = rnorm(25, mean = 5, sd = 4)


z_scores = function(x) {
      
    z = (x - mean(x)) / sd(x)
    
    return(z)
}

z_scores(x = x_vec)

y_vec = rnorm(40, mean = 12, sd = .3)

z_scores(y_vec)
```

How great is this?

```{r error = TRUE}
z_scores(3)

z_scores(c("my", "name", "is", "zak"))

z_scores(mtcars)
```

Let's try again.

```{r error = TRUE}
z_scores = function(x) {
      
      if(!is.numeric(x)) {
            stop("x needs to be numeric")
      }
      
      if(length(x) < 3) {
            stop("x should have at least 3 numbers")
      }
      
      z = (x - mean(x)) / sd(x)
      
      return(z)
}

# Should break
z_scores(mtcars)

# Should work
z_scores(y_vec)
```
